#Creating a file Makefile.config.local will allow some or all of these values to be overwritten (it will be imported after this file).
#BASE=/home/ali/tmp/rtc
BASE=/rtc
BIN=$(BASE)/bin
LIB=$(BASE)/lib
PY=$(LIB)/python
IDL=$(BASE)/idl
ETC=$(BASE)/etc
SRC=$(BASE)/src
CONF=$(BASE)/conf
TEST=$(BASE)/test
INC=$(BASE)/include
DOC=$(BASE)/doc

