all:

include ../Makefile.config

install:
	cp config*.py $(CONF)
	cp plot*.xml $(CONF)
	cp init*.py $(CONF)
	cp rtcguirc.py $(CONF)
	cp Makefile $(CONF)
	chmod a+r config*.py
	chmod a+r plot*.xml
	chmod a+r init*.py
	chmod a+r rtcguirc.py
	chmod a+r Makefile
