all:

include ../Makefile.config

install:
	cp agbcblas.h $(INC)
	cp circ.h $(INC)
	cp darc.h $(INC)
	cp darcNames.h $(INC)
	cp paramNames.h $(INC)
	cp qsort.h $(INC)
	cp rtcrecon.h $(INC)
	cp rtccamera.h $(INC)
	cp rtccentroider.h $(INC)
	cp rtcfigure.h $(INC)
	cp rtcmirror.h $(INC)
	cp arrayStruct.h $(INC)
	cp Makefile $(INC)

installdev:
	echo Done
